### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '\x00'.

### ISSUE THREAD

**Issue by Anandktr** [yunjey/pytorch-tutorial#131]
Hi all!
while running sample.py, this error comes up
Traceback (most recent call last):
File "sample.py", line 85, in <module>
main(args)
File "sample.py", line 47, in main
encoder.load_state_dict(torch.load(args.encoder_path))
File "C:\Anaconda3\lib\site-packages\torch\serialization.py", line 358, in load
return _load(f, map_location, pickle_module)
File "C:\Anaconda3\lib\site-packages\torch\serialization.py", line 532, in _load
magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, '\x00'.

Any solution for this..?

**Comment by anjalinagel12** [comment]
I got the same error. Please help me out.
Thanks in advance :)

**Comment by Anirudh257** [comment]
Try using torch.load instead of pickle.load.

**Comment by dmichaels713** [comment]
I am getting the exact same error regardless of if I use pickle.load or torch.load.  Any help would be appreciated.

UnpicklingError: invalid load key, '\x00'.

**Comment by AslantheAslan** [comment]
I am facing the same problem, could one of you guys come with a solution? That would be really helpful for me.
