### ISSUE TITLE
  File "build_vocab.py", line 1, in <module>

### ISSUE THREAD

**Issue by anjalinagel12** [yunjey/pytorch-tutorial#156]
![screenshot 2019-01-28 at 8 07 21 pm](https://user-images.githubusercontent.com/29358217/51843156-6a4bbd00-2338-11e9-84c1-18acb2b60d5f.png)

Traceback (most recent call last):
  File "build_vocab.py", line 1, in <module>
    import nltk
  File "/anaconda3/lib/python3.6/site-packages/nltk/__init__.py", line 128, in <module>
    from nltk.chunk import *
  File "/anaconda3/lib/python3.6/site-packages/nltk/chunk/__init__.py", line 157, in <module>
    from nltk.chunk.api import ChunkParserI
  File "/anaconda3/lib/python3.6/site-packages/nltk/chunk/api.py", line 15, in <module>
    from nltk.chunk.util import ChunkScore
  File "/anaconda3/lib/python3.6/site-packages/nltk/chunk/util.py", line 13, in <module>
    from nltk.tag.mapping import map_tag
  File "/anaconda3/lib/python3.6/site-packages/nltk/tag/__init__.py", line 70, in <module>
    from nltk.tag.sequential    import (SequentialBackoffTagger, ContextTagger,
  File "/anaconda3/lib/python3.6/site-packages/nltk/tag/sequential.py", line 26, in <module>
    from nltk.classify import NaiveBayesClassifier
  File "/anaconda3/lib/python3.6/site-packages/nltk/classify/__init__.py", line 98, in <module>
    from nltk.classify.textcat import TextCat
  File "/anaconda3/lib/python3.6/site-packages/nltk/classify/textcat.py", line 47, in <module>
    import regex as re
  File "/anaconda3/lib/python3.6/site-packages/regex.py", line 683, in <module>
    _pattern_type = type(_compile("", 0, {}))
  File "/anaconda3/lib/python3.6/site-packages/regex.py", line 436, in _compile
    pattern_locale = _getlocale()[1]
  File "/anaconda3/lib/python3.6/locale.py", line 581, in getlocale
    return _parse_localename(localename)
  File "/anaconda3/lib/python3.6/locale.py", line 490, in _parse_localename
    raise ValueError('unknown locale: %s' % localename)
ValueError: unknown locale: UTF-8

**Comment by anjalinagel12** [comment]
Someone please help

**Comment by anjalinagel12** [comment]
What's wrong with this?

**Comment by anjalinagel12** [comment]
SOLUTION: 
just write this-

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
