### ISSUE TITLE
Error on the project 

### ISSUE THREAD

**Issue by AIAdventures** [yunjey/pytorch-tutorial#23]
project 11 - linux python3.5

Files already downloaded and verified
Epoch [0/50], Step[100/500], d_loss: 1.1626, g_loss: 0.9049, D(x): 0.70, D(G(z)): 0.54
Traceback (most recent call last):
  File "main.py", line 130, in <module>
    './data/fake_samples_%d_%d.png' %(epoch+1, i+1))
  File "/home/andrewcz/miniconda3/lib/python3.5/site-packages/torchvision-0.1.8-py3.5.egg/torchvision/utils.py", line 95, in save_image
  File "/home/andrewcz/miniconda3/lib/python3.5/site-packages/PIL/Image.py", line 1682, in save
    fp = builtins.open(filename, "wb")
FileNotFoundError: [Errno 2] No such file or directory: './data/fake_samples_1_100.png'

Having trouble with this example.

**Comment by yunjey** [comment]
Create a folder named `data`.
