### ISSUE TITLE
output length of image captioning?

### ISSUE THREAD

**Issue by jtoy** [yunjey/pytorch-tutorial#38]
i am testing out different lengths of text for the caption of an image and I always get out of memory if I go over 200 characters.  I am using Titan X 12 GB and I have 64 GB of ram. it seems like this shouldnt die with out of memory issues  on 200 characters. How can I get a longer sequence outputted?  If I implement beam search, would that resolve this? I also tried cpu mode for sampling and get the same error:

`python sample.py --num_layers=3 --length=300 --vocab_path=./models/v2/vocab.pkl --image=/home/jtoy/sandbox/06.jpg
der=./models/v2/encoder-60-532.pkl --num_layers=3
THCudaCheck FAIL file=/py/conda-bld/pytorch_1493680494901/work/torch/lib/THC/generic/THCStorage.cu line=66 error=2 : out of memory
Traceback (most recent call last):
  File "sample.py", line 95, in <module>
    main(args)
  File "sample.py", line 54, in main
    sampled_ids = decoder.sample(feature, state,args.length)
  File "/home/jtoy/sandbox/pytorch/model.py", line 60, in sample
    hiddens, states = self.lstm(inputs, states)          # (batch_size, 1, hidden_size)
  File "/home/jtoy/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/jtoy/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 91, in forward
    output, hidden = func(input, self.all_weights, hx)
  File "/home/jtoy/anaconda3/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 343, in forward
    return func(input, *fargs, **fkwargs)
  File "/home/jtoy/anaconda3/lib/python3.6/site-packages/torch/autograd/function.py", line 202, in _do_forward
    flat_output = super(NestedIOFunction, self)._do_forward(*flat_input)
  File "/home/jtoy/anaconda3/lib/python3.6/site-packages/torch/autograd/function.py", line 224, in forward
    result = self.forward_extended(*nested_tensors)
  File "/home/jtoy/anaconda3/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 285, in forward_extended
    cudnn.rnn.forward(self, input, hx, weight, output, hy)
  File "/home/jtoy/anaconda3/lib/python3.6/site-packages/torch/backends/cudnn/rnn.py", line 272, in forward
    fn.workspace = torch.cuda.ByteTensor(workspace_size.value)
RuntimeError: cuda runtime error (2) : out of memory at /py/conda-bld/pytorch_1493680494901/work/torch/lib/THC/generic/THCStorage.cu:66`

**Comment by jtoy** [comment]
@yunjey fixed this by making the state volatile in sample:

    state = (Variable(torch.zeros(args.num_layers, 1, args.hidden_size),volatile=True),
             Variable(torch.zeros(args.num_layers, 1, args.hidden_size),volatile=True))

Found that from reading this: https://discuss.pytorch.org/t/optimizing-cuda-memory-pipeline-for-rnn/3311/3
