### ISSUE TITLE
Error at sample.py

### ISSUE THREAD

**Issue by sigmoidx** [yunjey/pytorch-tutorial#39]
When I followed the command: **_python sample.py --image='png/example.png'_**, it returns an error:

```
<start> guest building storing guest next gazelle 6 drawing guest applied pate <end>
Traceback (most recent call last):
  File "sample.py", line 96, in <module>
    main(args)
  File "sample.py", line 75, in main
    plt.imshow(np.asarray(image))
  File "/home/marsha/anaconda2/lib/python2.7/site-packages/matplotlib/pyplot.py", line 3029, in imshow
    **kwargs)
  File "/home/marsha/anaconda2/lib/python2.7/site-packages/matplotlib/__init__.py", line 1819, in inner
    return func(ax, *args, **kwargs)
  File "/home/marsha/anaconda2/lib/python2.7/site-packages/matplotlib/axes/_axes.py", line 4922, in imshow
    im.set_data(X)
  File "/home/marsha/anaconda2/lib/python2.7/site-packages/matplotlib/image.py", line 449, in set_data
    raise TypeError("Image data can not convert to float")
TypeError: Image data can not convert to float

```

**Comment by yunjey** [comment]
@sigmoidx  Thanks for noting the bug. I fixed the code. Check [here](https://github.com/yunjey/pytorch-tutorial/tree/master/tutorials/03-advanced/image_captioning#pretrained-model) and download the pretrained model and vocabulary file again. 

Now, the code works well.

![example](https://cloud.githubusercontent.com/assets/15663219/26538419/8e8b2760-4481-11e7-83d5-bc81a9f633c5.png)
