### ISSUE TITLE
Error in Image Captioning

### ISSUE THREAD

**Issue by wuneng** [yunjey/pytorch-tutorial#50]
Hi,I retrain Image Captioning model.It works well in training,but failed in testing.Here is my error.

xiang@xiang-Z270X-Gaming-K7:~/pytorch-tutorial/tutorials/03-advanced/image_captioning$ python sample.py --image='png/example.png'
showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml
Traceback (most recent call last):
  File "sample.py", line 97, in <module>
    main(args)
  File "sample.py", line 61, in main
    sampled_ids = decoder.sample(feature)
  File "/home/xiang/pytorch-tutorial/tutorials/03-advanced/image_captioning/model.py", line 62, in sample
    hiddens, states = self.lstm(inputs, states)          # (batch_size, 1, hidden_size), 
  File "/home/xiang/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 225, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/xiang/anaconda3/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 91, in forward
    output, hidden = func(input, self.all_weights, hx)
  File "/home/xiang/anaconda3/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 343, in forward
    return func(input, *fargs, **fkwargs)
  File "/home/xiang/anaconda3/lib/python3.6/site-packages/torch/autograd/function.py", line 284, in _do_forward
    flat_output = super(NestedIOFunction, self)._do_forward(*flat_input)
  File "/home/xiang/anaconda3/lib/python3.6/site-packages/torch/autograd/function.py", line 306, in forward
    result = self.forward_extended(*nested_tensors)
  File "/home/xiang/anaconda3/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 285, in forward_extended
    cudnn.rnn.forward(self, input, hx, weight, output, hy)
  File "/home/xiang/anaconda3/lib/python3.6/site-packages/torch/backends/cudnn/rnn.py", line 205, in forward
    'input must have 3 dimensions, got {}'.format(input.dim()))
RuntimeError: input must have 3 dimensions, got 2

**Comment by mhsamavatian** [comment]
I got the same error. How did you resolve this problem?
