### ISSUE TITLE
Imae Captioning Pickle Error

### ISSUE THREAD

**Issue by ahkarami** [yunjey/pytorch-tutorial#65]
Hi, 
I want to use the pre-trained models (without download MS-COCO Dataset). when i run the 
`python2 sample.py --image='png/example.png'` 
I got this error:

```
Traceback (most recent call last):
  File "sample.py", line 97, in <module>
    main(args)
  File "sample.py", line 37, in main
    vocab = pickle.load(f)
  File "/home/karami/anaconda2/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/home/karami/anaconda2/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/home/karami/anaconda2/lib/python2.7/pickle.py", line 1096, in load_global
    klass = self.find_class(module, name)
  File "/home/karami/anaconda2/lib/python2.7/pickle.py", line 1132, in find_class
    klass = getattr(mod, name)
AttributeError: 'module' object has no attribute 'Vocabulary'

```

**Comment by yunjey** [comment]
@ahkarami  You should save the vocabulary file to **'./data/vocab.pkl`**. If you want to use pretrained model, download the vocab file and unpack it as mentioned in ReadME.md.

**Comment by ahkarami** [comment]
@yunjey Thank you for your response. The code works correctly.
