### ISSUE TITLE
 I met this error: 

### ISSUE THREAD

**Issue by bemoregt** [yunjey/pytorch-tutorial#70]
Hi, @jtoy @hunkim @Kongsea @DingKe @JayParks 

I met this error:

sgiO2:image_captioning sgi$ python build_vocab.py 
loading annotations into memory...
Traceback (most recent call last):
  File "build_vocab.py", line 77, in <module>
    main(args)
  File "build_vocab.py", line 59, in main
    threshold=args.threshold)
  File "build_vocab.py", line 31, in build_vocab
    coco = COCO(json)
  File "/Library/Python/2.7/site-packages/pycocotools/coco.py", line 84, in __init__
    dataset = json.load(open(annotation_file, 'r'))
IOError: [Errno 2] No such file or directory: '/usr/share/mscoco/annotations/captions_train2014.json'

What's wrong with me?

**Comment by yunjey** [comment]
Sorry for the late reply. This has been fixed in the current version.
