### ISSUE TITLE
RuntimeError: invalid argument 2: out of range 

### ISSUE THREAD

**Issue by LidaGuan** [yunjey/pytorch-tutorial#71]
I met some problem in the code of image_captioning.
I have already trained the model and when I run the python sample.py --image='png/example.png' I got this error:

Traceback (most recent call last):
  File "sample.py", line 97, in <module>
    main(args)
  File "sample.py", line 61, in main
    sampled_ids = decoder.sample(feature)
  File "/home/guanlida/pytorch-tutorial/tutorials/03-advanced/image_captioning/model.py", line 68, in sample
    sampled_ids = torch.cat(sampled_ids, 1)                  # (batch_size, 20)
  File "/home/guanlida/anaconda2/envs/py3/lib/python3.6/site-packages/torch/autograd/variable.py", line 897, in cat
    return Concat.apply(dim, *iterable)
  File "/home/guanlida/anaconda2/envs/py3/lib/python3.6/site-packages/torch/autograd/_functions/tensor.py", line 316, in forward
    ctx.input_sizes = [i.size(dim) for i in inputs]
  File "/home/guanlida/anaconda2/envs/py3/lib/python3.6/site-packages/torch/autograd/_functions/tensor.py", line 316, in <listcomp>
    ctx.input_sizes = [i.size(dim) for i in inputs]
RuntimeError: invalid argument 2: out of range at /opt/conda/conda-bld/pytorch_1503970438496/work/torch/lib/THC/generic/THCTensor.c:23

I don't know the reason of the error, can anyone help me to solve it?

**Comment by LidaGuan** [comment]
I have solved the error in the sample.py and I found that the code in model.py have some problem.
I change the line 68 of model.py to
sampled_ids = torch.cat(sampled_ids, 0)
