### ISSUE TITLE
RuntimeError: invalid argument 2: out of range

### ISSUE THREAD

**Issue by bemoregt** [yunjey/pytorch-tutorial#72]
HI, @jtoy @hunkim @Kongsea @DingKe @JayParks 

I met this error in image caption run:

kraken@devBox1:~/pytorch-tutorial/tutorials/03-advanced/image_captioning$ sudo python3 sample.py --image='./png/example.png' 
[sudo] password for kraken: 
Traceback (most recent call last):
  File "sample.py", line 97, in <module>
    main(args)
  File "sample.py", line 61, in main
    sampled_ids = decoder.sample(feature)
  File "/home/kraken/pytorch-tutorial/tutorials/03-advanced/image_captioning/model.py", line 68, in sample
    sampled_ids = torch.cat(sampled_ids, 1)                  # (batch_size, 20)
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/variable.py", line 897, in cat
    return Concat.apply(dim, *iterable)
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/_functions/tensor.py", line 316, in forward
    ctx.input_sizes = [i.size(dim) for i in inputs]
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/_functions/tensor.py", line 316, in <listcomp>
    ctx.input_sizes = [i.size(dim) for i in inputs]
RuntimeError: invalid argument 2: out of range at /pytorch/torch/lib/THC/generic/THCTensor.c:23
kraken@devBox1:~/pytorch-tutorial/tutorials/03-advanced/image_captioning$ 

What's wrong with me ?

**Comment by intuinno** [comment]
Hello, you can change the line 68 of model.py. 

Original
```python
sampled_ids = torch.cat(sampled_ids, 1)  
```

Changed
```python
sampled_ids` = torch.cat(sampled_ids, 0)  
```

**Comment by yunjey** [comment]
Sorry for the late reply. This has been fixed in the current version.
