### ISSUE TITLE
captioning code doesn't run

### ISSUE THREAD

**Issue by ShasTheMass** [yunjey/pytorch-tutorial#75]
Hi. I am getting the error below. I hope someone can help @jtoy 
```

python sample.py --image='png/example.png'
Traceback (most recent call last):
  File "sample.py", line 97, in <module>
    main(args)
  File "sample.py", line 61, in main
    sampled_ids = decoder.sample(feature)
  File "/home/shas/sandbox/pytorch-tutorial/tutorials/03-advanced/image_captioning/model.py", line 62, in sample
    hiddens, states = self.lstm(inputs, states)          # (batch_size, 1, hidden_size), 
  File "/home/shas/miniconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/shas/miniconda2/lib/python2.7/site-packages/torch/nn/modules/rnn.py", line 91, in forward
    output, hidden = func(input, self.all_weights, hx)
  File "/home/shas/miniconda2/lib/python2.7/site-packages/torch/nn/_functions/rnn.py", line 343, in forward
    return func(input, *fargs, **fkwargs)
  File "/home/shas/miniconda2/lib/python2.7/site-packages/torch/nn/_functions/rnn.py", line 243, in forward
    nexth, output = func(input, hidden, weight)
  File "/home/shas/miniconda2/lib/python2.7/site-packages/torch/nn/_functions/rnn.py", line 83, in forward
    hy, output = inner(input, hidden[l], weight[l])
  File "/home/shas/miniconda2/lib/python2.7/site-packages/torch/nn/_functions/rnn.py", line 112, in forward
    hidden = inner(input[i], hidden, *weight)
  File "/home/shas/miniconda2/lib/python2.7/site-packages/torch/nn/_functions/rnn.py", line 30, in LSTMCell
    gates = F.linear(input, w_ih, b_ih) + F.linear(hx, w_hh, b_hh)
  File "/home/shas/miniconda2/lib/python2.7/site-packages/torch/nn/functional.py", line 449, in linear
    return state(input, weight) if bias is None else state(input, weight, bias)
  File "/home/shas/miniconda2/lib/python2.7/site-packages/torch/nn/_functions/linear.py", line 10, in forward
    output.addmm_(0, 1, input, weight.t())
RuntimeError: matrices expected, got 3D, 2D tensors at /opt/conda/conda-bld/pytorch_1501972792122/work/pytorch-0.1.12/torch/lib/TH/generic/THTensorMath.c:1232
```

I have tried with both `pytorch=0.1.12` and `pytorch=0.2`. None work!

**Comment by brucepang** [comment]
Same error here. Don't know how to solve

**Comment by zaghlol94** [comment]
Same error here.

**Comment by yunjey** [comment]
Sorry for the late reply. This has been fixed in the current version.
