### ISSUE TITLE
Image Caption sample code

### ISSUE THREAD

**Issue by lxtGH** [yunjey/pytorch-tutorial#80]
I can **train** the model as your guidence 
but when I run sample.py using pretrained model, Error hapened 
It says **dimension error of input to LSTM, But I print the size or dim, everything is ok**
In the model.py file 
lxt@slave-01:~/pytorch/study/pytorch-tutorial-master/tutorials/03-advanced/image_captioning$ python sample.py --image='png/example.png'
3
Traceback (most recent call last):
  File "sample.py", line 97, in <module>
    main(args)
  File "sample.py", line 61, in main
    sampled_ids = decoder.sample(feature)
  File "/home/lxt/pytorch/study/pytorch-tutorial-master/tutorials/03-advanced/image_captioning/model.py", line 73, in sample
    hiddens, states = self.lstm(inputs, states)  # (batch_size, 1, hidden_size),
  File "/home/lxt/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lxt/anaconda2/lib/python2.7/site-packages/torch/nn/modules/rnn.py", line 162, in forward
    output, hidden = func(input, self.all_weights, hx)
  File "/home/lxt/anaconda2/lib/python2.7/site-packages/torch/nn/_functions/rnn.py", line 351, in forward
    return func(input, *fargs, **fkwargs)
  File "/home/lxt/anaconda2/lib/python2.7/site-packages/torch/autograd/function.py", line 284, in _do_forward
    flat_output = super(NestedIOFunction, self)._do_forward(*flat_input)
  File "/home/lxt/anaconda2/lib/python2.7/site-packages/torch/autograd/function.py", line 306, in forward
    result = self.forward_extended(*nested_tensors)
  File "/home/lxt/anaconda2/lib/python2.7/site-packages/torch/nn/_functions/rnn.py", line 293, in forward_extended
    cudnn.rnn.forward(self, input, hx, weight, output, hy)
  File "/home/lxt/anaconda2/lib/python2.7/site-packages/torch/backends/cudnn/rnn.py", line 208, in forward
    'input must have 3 dimensions, got {}'.format(input.dim()))
RuntimeError: input must have 3 dimensions, got 2

**Comment by lxtGH** [comment]
It seems like a version problems
Using python3 It can run , I don't why
