### ISSUE TITLE
Error about nltk punkt

### ISSUE THREAD

**Issue by SilencerChen** [yunjey/pytorch-tutorial#82]
I have install nltk, and I put the nltk_data in the right path. But when I run build_vocab.py , I got this. 

loading annotations into memory...
Done (t=0.52s)
creating index...
index created!
Traceback (most recent call last):
  File "build_vocab.py", line 77, in <module>
    main(args)
  File "build_vocab.py", line 59, in main
    threshold=args.threshold)
  File "build_vocab.py", line 36, in build_vocab
    tokens = nltk.tokenize.word_tokenize(caption.lower())
  File "/home/fkc/.conda/envs/torch36/lib/python3.6/site-packages/nltk/tokenize/__init__.py", line 128, in word_tokenize
    sentences = [text] if preserve_line else sent_tokenize(text, language)
  File "/home/fkc/.conda/envs/torch36/lib/python3.6/site-packages/nltk/tokenize/__init__.py", line 94, in sent_tokenize
    tokenizer = load('tokenizers/punkt/{0}.pickle'.format(language))
  File "/home/fkc/.conda/envs/torch36/lib/python3.6/site-packages/nltk/data.py", line 834, in load
    opened_resource = _open(resource_url)
  File "/home/fkc/.conda/envs/torch36/lib/python3.6/site-packages/nltk/data.py", line 952, in _open
    return find(path_, path + ['']).open()
  File "/home/fkc/.conda/envs/torch36/lib/python3.6/site-packages/nltk/data.py", line 673, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')
  
  Searched in:
    - '/home/fkc/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - '/home/fkc/.conda/envs/torch36/nltk_data'
    - '/home/fkc/.conda/envs/torch36/lib/nltk_data'
    - ''
**********************************************************************

What should I do to fix it . I use python3.6 by the way.

**Comment by h-harshit** [comment]
The solution is right there just below look up error

import nltk
nltk.download('punkt')
